# Generated by Django 5.0.1 on 2024-01-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_services_id_alter_services_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='services',
            table=None,
        ),
    ]
