# Generated by Django 5.0.1 on 2024-01-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_services_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('designation', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='team_images/')),
            ],
        ),
    ]
