# Generated by Django 5.0.1 on 2024-01-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_protfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protfolio',
            name='category',
        ),
        migrations.AddField(
            model_name='protfolio',
            name='category',
            field=models.ManyToManyField(to='blog_app.category'),
        ),
    ]
