# Generated by Django 5.0.1 on 2024-01-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
    ]
