# Generated by Django 5.0.1 on 2024-01-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_rename_email_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='asd',
            fields=[
                ('abc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog_app.abc')),
                ('title', models.CharField(max_length=90)),
            ],
            bases=('blog_app.abc',),
        ),
        migrations.CreateModel(
            name='xyz',
            fields=[
                ('abc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog_app.abc')),
                ('title', models.CharField(max_length=30)),
            ],
            bases=('blog_app.abc',),
        ),
    ]
